[build]
builder = "nixpacks"
buildCommand = "./mvnw -DskipTests package"

[deploy]
startCommand = "java -jar target/solo-music-academy-0.0.1-SNAPSHOT.jar"
restartPolicyType = "on_failure"
healthcheckPath = "/health"
