[build]
builder = "nixpacks"

[build.nixpacks]
plan = "java"

[build.nixpacks.env]
JAVA_VERSION = "17"

[build.nixpacks.phases.build]

cmd = "mvn -DskipTests package"

[build.nixpacks.phases.start]
cmd = "java -jar target/solo-music-academy-0.0.1-SNAPSHOT.jar"
